SOUNDS = {
    'entrada_del_bosque': 'forest_entrance.wav',
    'espiritu': 'spirit.wav',
    'caminar': 'steps.wav',
    'recoger': 'grab_item.wav',
    'objeto_sagrado': 'sacred_object.wav',
    'ver': 'look.wav',
    'hablar': {'Cueva Oscura': 'spirit_voice.wav', 'Árbol de los Susurros': 'whispering_tree.wav', 'Puente Roto': 'guardian.wav'},
    'atacar': 'attack.wav',
    'defender': 'defend.wav',
    'huir': 'run_away.wav',
    'Guardia de las Sombras': 'monster_attack.wav',
    'enemigo_derrotado': 'enemy_defeated.wav',
    'cueva_oscura': 'wolf.wav',
    'Serpiente del Lago': 'snake.wav',
    'árbol_de_los_susurros': 'forest_entrance.wav',
    'arbol': 'tree.wav',
    'claro_del_bosque': 'clearing.wav',
    'lago_negro': 'lake.wav',
    'balsa': 'building_boat.wav',
    'navegar': 'boat_move.wav',
    'altar_de_piedra': 'forest_entrance.wav',
    'explorador_derrotado': 'player_death.wav',
    'puente_roto': 'bridge.wav',
}